### ISSUE TITLE
error 'chalk'

### ISSUE THREAD

**Issue by maulvi** [seanc/kdownload#1]
Hi
i got this error when running kdl -h

`root@animeba:~# kdl

module.js:340
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/kdownload/node_modules/zt/lib/index.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)`

**Comment by jarildson** [comment]
He didn't add chalk as a dependency. If you can get a windows machine, do this in admin CMD: `C:\Users\username\AppData\Roaming\npm>npm install chalk`

**Comment by seanc** [comment]
Sorry about that, will ge t athat resolved asap.!

**Comment by jamen** [comment]
:+1:
